vitalij99/recipes5

- src/styles/theme.js
> Global Colors/Hovers 

- src/styles/theme.js
> Dark theme

- src/components/Container/Container.style.js
- src/components/IngredientsShoppingList/IngredientsShoppingList.jsx
- src/components/IngredientsShoppingList/IngredientsShoppingList.styled.js
- src/components/MainPageTitle/MainPageTitle.jsx
- src/components/MainPageTitle/MainPageTitle.styled.js
- src/page/ShoppingListPage/ShoppingListPage.jsx
- src/styles/theme.js
MainPageTitle component done fix theme
> MainPageTitle component done fix theme

- src/components/Header/Header.jsx
- src/components/IngredientsShoppingList/IngredientsShoppingList.jsx
- src/components/IngredientsShoppingList/IngredientsShoppingList.styled.js
- src/components/IngredientsShoppingList/ListItem.jsx
- src/components/MainPageTitle/MainPageTitle.styled.js
> Fix mainpagetitle size

- src/components/AddRecipe/AddRecipeForm.jsx
- src/components/Footer/Footer.styled.jsx
- src/styles/GlobalStyles.js
global-animation-button-div-svg-a
> global-animation-button-div-svg-a

- src/components/AddRecipe/AddRecipe.styled.js
- src/components/AddRecipe/AddRecipeForm.jsx
- src/components/AddRecipe/RecipeDescription/RecipeDescription.styled.js
- src/components/AddRecipe/RecipeDescription/RecipeDescriptionFields.jsx
- src/components/AddRecipe/RecipeIngredients/RecipeIngredients.styled.js
- src/components/AddRecipe/RecipeIngredients/RecipeIngredientsFields.jsx
- src/components/AddRecipe/RecipePreparation/RecipePreparation.styled.js
- src/components/AddRecipe/RecipePreparation/RecipePreparationFields.jsx
- src/styles/theme.js
> tablet-desktop

- src/components/Search/SearchBar/SearchBar.jsx
- src/components/Search/SearchBar/SearchBar.styled.js
- src/components/Search/SearchTypeSelector/Dropdown.jsx
- src/components/Search/SearchTypeSelector/Dropdown.styled.js
- src/components/Search/SearchTypeSelector/SearchTypeSelector.jsx
- src/components/Search/SearchTypeSelector/SearchTypeSelector.styled.js
- src/components/Search/SearchedRecipesList/SearchRecipesList.jsx
- src/components/Search/SearchedRecipesList/SearchRecipesList.styled.js
- src/page/SearchPage/SearchPage.jsx
- src/styles/GlobalStyles.js
- src/styles/theme.js
shearchPage
created component SearchTypeSelector for all screen sizes.
> Search page styles

- package-lock.json
- package.json
- src/components/Loader/Loader.jsx
- src/components/Loader/Loader.styled.js
- src/page/AddRecipePage/AddRecipePage.jsx
- src/styles/theme.js
added loader and styles, as well added global styles for loader
> added loader and styles

- src/components/App.js
- src/components/IngredientsShoppingList/IngredientsShoppingList.jsx
- src/components/IngredientsShoppingList/IngredientsShoppingList.styled.js
- src/components/SharedLayout/SharedLayout.jsx
- src/index.js
- src/styles/GlobalStyles.js
> fix-global-page-layout

- src/components/Search/SearchTypeSelector/Dropdown.jsx
- src/styles/GlobalStyles.js
> bg-color-main-fix-global

- src/components/IngredientsShoppingList/IngredientsShoppingList.jsx
- src/components/IngredientsShoppingList/IngredientsShoppingList.styled.js
- src/components/IngredientsShoppingList/ListSection.jsx
- src/components/Search/SearchBar/SearchBar.jsx
- src/components/Search/SearchForm/SearchFrom.jsx
- src/styles/GlobalStyles.js
> shopping-list-connected

- src/components/MainPage/Hero/Hero.jsx
- src/components/Search/SearchBar/SearchBar.jsx
- src/components/Search/SearchForm/SearchForm.styled.js
- src/components/Search/SearchForm/SearchFrom.jsx
> Shearch from

- src/components/IngredientsShoppingList/IngredientsShoppingList.styled.js
- src/components/Search/SearchTypeSelector/Dropdown.jsx
- src/styles/theme.js
> color-changes

- src/components/Footer/SocialIcons/SocialIcons.jsx
- src/components/Footer/SocialIcons/SocialIcons.styled.jsx
> fix-footer-imports

- src/components/Categories/CardItem.jsx
- src/components/Categories/Categories.jsx
- src/components/Search/SearchedRecipesList/SearchRecipesList.jsx
> cardItem-list used

- src/components/MyRecipes/MyRecipes.jsx
- src/components/MyRecipes/MyRecipes.styled.jsx
- src/page/MyRecipesPage/MyRecipesPage.jsx
додав новий компонент , щоб було легше робити логіку
> added a new component

- src/components/AddRecipe/PopularRecipe/PopularRecipe.styled.js
- src/components/AddRecipe/PopularRecipe/SocialIcons.styled.js
- src/components/AddRecipe/RecipeDescription/RecipeDescription.styled.js
- src/components/AddRecipe/RecipeDescription/RecipeDescriptionFields.jsx
- src/components/AddRecipe/RecipeIngredients/BtnDeleteIcon.jsx
- src/components/AddRecipe/RecipeIngredients/RecipeIngredients.styled.js
- src/components/AddRecipe/RecipeIngredients/RecipeIngredientsFields.jsx
- src/components/AddRecipe/RecipePreparation/RecipePreparation.styled.js
- src/components/AddRecipe/validationForm.js
- src/components/Footer/SocialIcons/SocialIcons.styled.js
- src/styles/GlobalStyles.js
- src/styles/theme.js
> some styles

- .gitignore
- src/components/Header/Header.jsx
- src/components/Header/Header.styled.jsx
- src/components/IngredientsShoppingList/IngredientsShoppingList.styled.js
- src/styles/GlobalStyles.js
> general-style-fixes

- src/components/Header/Header.jsx
> fix-header

- src/components/AddRecipe/AddRecipeForm.jsx
- src/components/AddRecipe/PopularRecipe/PopularRecipe.jsx
- src/components/IngredientsShoppingList/IngredientsShoppingList.jsx
- src/components/Loader/Loader.jsx
- src/components/Loader/Loader.styled.js
- src/components/SharedLayout/SharedLayout.jsx
fixed loader (full screen), added loader to addRecipe
> loader fix

- .gitignore
- .vscode/settings.json
- src/components/IngredientsShoppingList/IngredientsShoppingList.jsx
- src/components/Search/SearchNotFound/SearchNotFound.jsx
- src/components/Search/SearchedRecipesList/SearchRecipesList.jsx
Shopping list empty placeholder
> Shopping list empty placeholder

- .vscode/settings.json
- src/components/Search/SearchedRecipesList/SearchRecipesList.jsx
- src/redux/search/searchOperations.js
- src/redux/search/searchSelectors.js
- src/redux/search/searchSlice.js
- src/redux/store.js
> search-state-slice-created

- src/redux/search/searchSlice.js
> fix-404-search

- src/components/FavoritePage/FavoritePage.jsx
- src/components/MyRecipes/MyRecipes.jsx
> fix-placeholder

- src/components/Search/SearchBar/SearchBar.jsx
- src/redux/search/searchSlice.js
> search-reset-fix

- package-lock.json
- package.json
- src/components/SharedLayout/SharedLayout.jsx
- src/components/ToTop/ToTop.jsx
- src/components/ToTop/ToTop.styled.js
- src/styles/theme.js
> to-top-created
